### ISSUE TITLE
Account console can't get UserSession

### ISSUE THREAD

**Issue by xgp** [xgp/keycloak-jpa-cache#11]
To reproduce:
1. `mvn clean install -DskipTests && docker compose up`
2. log into the admin console
3. create a realm
4. add a user to the realm and give a password
5. load the account console and log in as the created user
6. click on the "Device activity" and "Applications" links

in the `DeviceActivityManager`:
```
2024-04-17 17:07:46,512 INFO  [io.phasetwo.keycloak.jpacache.JpaCacheDatastoreProviderFactory] (executor-thread-2) Creating JpaCacheDatastoreProvider...
2024-04-17 17:07:46,514 TRACE [io.phasetwo.keycloak.jpacache.userSession.JpaCacheUserSessionProvider] (executor-thread-2) getUserSession(967aa904-97e4-4bfa-bbad-1e0166a45f24@856136f7, 7be511ac-7122-43a5-8027-c8f0c0ffd961)
2024-04-17 17:07:46,519 TRACE [io.phasetwo.keycloak.jpacache.singleUseObject.JpaCacheSingleUseObjectProvider] (executor-thread-2) contains(231c1eae-864a-42b1-ac8d-545f8a139a72.revoked)
2024-04-17 17:07:46,520 TRACE [io.phasetwo.keycloak.jpacache.userSession.JpaCacheUserSessionProvider] (executor-thread-2) getUserSession(967aa904-97e4-4bfa-bbad-1e0166a45f24@856136f7, 7be511ac-7122-43a5-8027-c8f0c0ffd961)
2024-04-17 17:07:46,522 TRACE [io.phasetwo.keycloak.jpacache.userSession.JpaCacheUserSessionProvider] (executor-thread-2) getUserSessionsStream(967aa904-97e4-4bfa-bbad-1e0166a45f24@856136f7, org.keycloak.models.cache.infinispan.UserAdapter@9d013ae3)
2024-04-17 17:07:46,530 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-2) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.UserSessionModel.getNote(String)" because "userSession" is null
  at org.keycloak.device.DeviceActivityManager.getCurrentDevice(DeviceActivityManager.java:43)
  at org.keycloak.services.resources.account.SessionResource.getAttachedDevice(SessionResource.java:184)
  at org.keycloak.services.resources.account.SessionResource.lambda$devices$1(SessionResource.java:89)
  at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
  at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
  at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
  at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
  at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
  at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
  at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
  at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
  at org.keycloak.services.resources.account.SessionResource.devices(SessionResource.java:88)
  at org.keycloak.services.resources.account.SessionResource$quarkusrestinvoker$devices_7f87e26d20b2e8eb6d8b3ced042b7ff2046c31dc.invoke(Unknown Source)
  at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
  at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
  at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
  at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
  at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
  at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
  at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
  at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  at java.base/java.lang.Thread.run(Thread.java:840)

2024-04-17 17:07:46,531 WARN  [io.agroal.pool] (executor-thread-2) Datasource '<default>': JDBC resources leaked: 1 ResultSet(s) and 1 Statement(s)
```

in the `AccountRestService`:
```
2024-04-17 17:08:16,724 INFO  [io.phasetwo.keycloak.jpacache.JpaCacheDatastoreProviderFactory] (executor-thread-2) Creating JpaCacheDatastoreProvider...
2024-04-17 17:08:16,727 TRACE [io.phasetwo.keycloak.jpacache.userSession.JpaCacheUserSessionProvider] (executor-thread-2) getUserSession(967aa904-97e4-4bfa-bbad-1e0166a45f24@856136f7, 7be511ac-7122-43a5-8027-c8f0c0ffd961)
2024-04-17 17:08:16,734 TRACE [io.phasetwo.keycloak.jpacache.singleUseObject.JpaCacheSingleUseObjectProvider] (executor-thread-2) contains(231c1eae-864a-42b1-ac8d-545f8a139a72.revoked)
2024-04-17 17:08:16,736 TRACE [io.phasetwo.keycloak.jpacache.userSession.JpaCacheUserSessionProvider] (executor-thread-2) getUserSession(967aa904-97e4-4bfa-bbad-1e0166a45f24@856136f7, 7be511ac-7122-43a5-8027-c8f0c0ffd961)
2024-04-17 17:08:16,739 TRACE [io.phasetwo.keycloak.jpacache.userSession.JpaCacheUserSessionProvider] (executor-thread-2) getUserSessionsStream(967aa904-97e4-4bfa-bbad-1e0166a45f24@856136f7, org.keycloak.models.cache.infinispan.UserAdapter@9d013ae3)
2024-04-17 17:08:16,747 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-2) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.UserSessionModel.getAuthenticatedClientSessions()" because "s" is null
  at org.keycloak.services.resources.account.AccountRestService.lambda$applications$3(AccountRestService.java:450)
  at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
  at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
  at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
  at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
  at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
  at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
  at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
  at org.keycloak.services.resources.account.AccountRestService.applications(AccountRestService.java:453)
  at org.keycloak.services.resources.account.AccountRestService$quarkusrestinvoker$applications_7e4d5772b3781c2331e05f25a7f914308c08b5bd.invoke(Unknown Source)
  at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
  at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
  at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
  at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
  at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
  at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
  at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
  at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  at java.base/java.lang.Thread.run(Thread.java:840)

2024-04-17 17:08:16,748 WARN  [io.agroal.pool] (executor-thread-2) Datasource '<default>': JDBC resources leaked: 1 ResultSet(s) and 1 Statement(s)
```

**Comment by xgp** [comment]
@rtufisi despite the tests on this passing, this is an example of fetching user sessions not working in the context of an application.

**Comment by xgp** [comment]
@rtufisi Thanks for finding that. 

It looks like there is some king of `StackOverflowError` getting thrown. Maybe some kind of self reference that needs to be checked?

Can you look a bit more into that? It should return the current user session.

**Comment by rtufisi** [comment]
I believe that expired sessions are automatically evicted in the casandra implementation by setting a TTL :
```
  @Override
  public void insertOrUpdate(UserSession session, int ttl) {
    BoundStatementBuilder boundStatementBuilder = insertOrUpdateStatement1.boundStatementBuilder();
    userSessionHelper.set(session, boundStatementBuilder, NullSavingStrategy.SET_TO_NULL, false);
    boundStatementBuilder = boundStatementBuilder.setInt("ttl", ttl);
    BoundStatement boundStatement = boundStatementBuilder.build();
    execute(boundStatement);
  }
```
