### ISSUE TITLE
outstanding tests

### ISSUE THREAD

**Issue by xgp** [xgp/keycloak-jpa-cache#3]
# fails
UserSessionProviderModelTest#testExpiredClientSessions
- `Caused by: java.lang.IllegalStateException: Session/EntityManager is closed`

UserSessionProviderModelTest#testTransientUserSessionIsNotPersisted
- `Expected: null
     but: was <io.phasetwo.keycloak.jpacache.userSession.JpaCacheUserSessionAdapter@d0bffb27>`

UserSessionProviderModelTest#testClientSessionIsNotPersistedForTransientUserSession
- `Expected: null
     but: was <io.phasetwo.keycloak.jpacache.userSession.JpaCacheUserSessionAdapter$1@91bc88fd>`

UserSessionProviderModelTest#testTransientUserSession
- `java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at io.phasetwo.keycloak.jpacache.testsuite.session.UserSessionProviderModelTest.lambda$testTransientUserSession$34(UserSessionProviderModelTest.java:758)`

UserSessionProviderModelTest#testGetByClient
- `array lengths differed, expected.length=3 actual.length=0; arrays first differed at element [0]; expected:<19e8bfb5-2e9b-4089-8ef2-d01fa31c0c81> but was:<end of array>`
- `Caused by: java.lang.AssertionError: expected:<19e8bfb5-2e9b-4089-8ef2-d01fa31c0c81> but was:<end of array>`

UserSessionProviderModelTest#testBrokerUserSessions
- `java.lang.IllegalArgumentException: Could not locate named parameter [brokerSessionId], expecting one of [realmId, brokerUserId]`
- `Caused by: org.hibernate.query.UnknownParameterException: Could not locate named parameter [brokerSessionId], expecting one of [realmId, brokerUserId]`

UserSessionProviderModelTest#testActiveClientSessionStats @rtufisi 
- method marked TODO - not yet implemented

UserSessionProviderModelTest#testRemoveSessions
- `java.lang.NullPointerException: Cannot invoke "io.phasetwo.keycloak.jpacache.userSession.persistence.entities.UserSession.getNotes()" because "userSessionEntity" is null
	at io.phasetwo.keycloak.jpacache.userSession.JpaCacheUserSessionProvider.getOfflineUserSessionEntityStream(JpaCacheUserSessionProvider.java:676)
	at io.phasetwo.keycloak.jpacache.userSession.JpaCacheUserSessionProvider.getOfflineUserSession(JpaCacheUserSessionProvider.java:471)
	at io.phasetwo.keycloak.jpacache.testsuite.session.UserSessionProviderModelTest.lambda$testRemoveSessions$58(UserSessionProviderModelTest.java:1328)`

UserSessionProviderModelTest#testImportUserSessions
- `Caused by: java.lang.IllegalStateException: Session/EntityManager is closed`

UserSessionExpirationTest#testClientSessionIdleTimeoutOverride
- `Expected: null
     but: was <io.phasetwo.keycloak.jpacache.userSession.JpaCacheUserSessionAdapter@321b307a>`

UserSessionExpirationTest#testClientSessionIdleTimeoutOverrideTtl
- `Expected: null
     but: was <io.phasetwo.keycloak.jpacache.userSession.JpaCacheUserSessionAdapter@5ecc1c91>`

UserSessionInitializerTest#testUserSessionInitializer @rtufisi 
- I don't think this is implemented yet
- `Expected: is <3L>
     but: was <0L>`

UserSessionInitializerTest#testUserSessionInitializerWithDeletingClient @rtufisi 
- I don't think this is implemented yet
- `Expected: is <1L>
     but: was <0L>`

# works
UserSessionProviderModelTest#testMultipleSessionsRemovalInOneTransaction
UserSessionProviderModelTest#testRemoveUserSession
UserSessionProviderModelTest#testRemoveUserSessionsByRealm
UserSessionConcurrencyTest#testConcurrentNotesChange
UserSessionProviderModelTest#testCreateSessions
UserSessionProviderModelTest#testUpdateSession
UserSessionProviderModelTest#testUpdateSessionInSameTransaction
UserSessionProviderModelTest#testRestartSession
UserSessionProviderModelTest#testCreateClientSession
UserSessionProviderModelTest#testUpdateClientSession
UserSessionProviderModelTest#testUpdateClientSessionWithGetByClientId
UserSessionProviderModelTest#testUpdateClientSessionInSameTransaction
UserSessionProviderModelTest#testGetUserSessions
UserSessionProviderModelTest#testRemoveUserSessionsByUser
UserSessionProviderModelTest#testOnClientRemoved
UserSessionProviderModelTest#testGetByClientPaginated
UserSessionProviderModelTest#testCreateAndGetInSameTransaction
UserSessionProviderModelTest#testAuthenticatedClientSessions
UserSessionProviderModelTest#testUserSessionNotes
UserSessionProviderModelTest#testClientSessionToUserSessionReference
UserSessionExpirationTest#testClientSessionIdleTimeout
UserSessionExpirationTest#testDeleteSession

**Comment by rtufisi** [comment]
Last test standing UserSessionInitializerTest. Please have a look @xgp
